[tool.poetry]
name = "kc-chatbot"
version = "0.1.0"
description = ""
authors = ["Torchme"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytelegrambotapi = "^4.14.0"
python-dotenv = "^1.0.0"
aiohttp = "^3.9.1"
openai = "^1.3.7"
pre-commit = "^3.5.0"
moviepy = "^1.0.3"
black = "22.10.0"
isort = "5.12.0"
pylint = "3.0.2"
pytest = "^6.2"
mypy = "1.7.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
