messages:
  welcome: |
    Привет! Я — *KarpovGPT*🤖, бот для помощи в обучении.
    Ты можешь *задавать вопросы* и *получать ответы* на основе курсов!
    А так же я могу помочь *создавать конспекты*👨‍💻!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога
