callback:
  approve:
    user: 
      to_admins: |
        ✅ Одобрено:\nusername: {username}\nuser_id: {user_id}\n\nЕсли захотите удалить пользователя, используйте /del_user [user_id] 
      to_user: |
        ✅ Спасибо за ожидание! Вам выдан доступ к боту
    channel: 
      to_user:
        ✅ Спасибо за ожидание! Канал {channel} был одобрен модерацией!
      to_admins: |
        ✅ Одобрено:\nchannel: {channel}\nЕсли захотите удалить канал, используйте /del_channel @[channel]
  deny:
      user:
        to_admins: |
          ❌ Отказано:\nusername: {username}\nuser_id: {user_id}
        to_user: |
          ❌ К сожалению, Вам отказано в доступе к боту
      channel: 
        to_user: |
          ❌Канал {channel} был  отклонен модерацией
        to_admins: |
          ❌ Отказано:\nchannel: {channel}
messages:
  welcome: |
    Привет! Я — *PostFinder*, инструмент, который изменит твое взаимодействие с социальными сетями.

    Если вы постоянно теряетесь в ТОННЕ КОНТЕНТА,
    приходиться листать БЕСКОНЕЧНОЕ количество постов и никак не можете найти ТОТ САМЫЙ пост? То вы пришли в нужное место!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога
    - /find `<@channel> <Запрос>` - ищет ответ на Ваш вопрос в указанном канале

    _Например: /find @postfinder Как найти нужный пост в группе?_
  errors:
    parse_error: |
      Аргументы не были переданы.\nПожалуйста, уточните канал и Ваш запрос, после команды\n\n_Например: /find @postfinder Как найти нужный пост в группе?_
    parse_channel_error: |
      Аргументы не были переданы.\n
    no_rights: |
      Error: You don't have rights for this.\n\nContact @redpf for rights
    unknown_message_error: |
      🚫 Я не распознал ваш запрос.

      Чтобы продолжить диалог, пожалуйста, ответьте на одно из предыдущих сообщений или воспользуйтесь командой:
      */find [Канал] [Запрос]*

  searching: |
    👀 Ищем ответы...
  
  moderation: 
    channel:
      processing: |
        Предложенный Вами канал в статусе рассмотрения администрацией, пожалуйста, ожидайте.
      deny: |
        
    user: 
      processing: |
        Вы еще не прошли модерацию, пожалуйста, ожидайте
      answer: |
        Ваш аккаунт в статусе рассмотрения модерацией, пожалуйста, ожидайте    
  action_to_continue: |
    🔹 Чтобы продолжить, ответьте на это сообщение    
  action_processed: |
    Action for user {} processed!
  unknown: |
    Упс... Похоже я не знаю такой команды 😬
  admin:
    remove:
      success: |
        User {} was removed
      fail: |
        User ID not found in the whitelist.
    add:
      success: |
        User {} was successfully added!
      fail: |
        User {} is already in whitelist!
  user: 
    registered: |
      User {} registered!
    already_registered: |
      User {} is already registered!


templates:
  extract: |
    Write the tags for the query below:
    ----------------------------------------
    Query: "{query}"
    ----------------------------------------
    Instruction:
    1) You must use language as in original query
    2) Do not duplicate the query in your response.
    3) Do not use words from original query in your response, your tags must be new and unique
    4) Write the tags in the order of relevance, separated by commas, without any other characters.

    Examples:
    Query: 'Какой рецепт борща?'
    Answer: 'Кулинария, суп'

    Query: 'Кто создал ChatGPT?'
    Answer: 'AI, OpenAI, LLM'

    Query: 'Что такое МЛ симулятор?'
    Answer: 'Машинное обучение, искусственный интеллект'
  prompt: |
   Answer the question based on the context below. Use language as in question. "\n\nContext: {context}\n\n---\n\nQuestion: {question}\nAnswer:
users:
  - 11

  - 326213970
admins:
  - 2
  - 326213970
